---
resources:
  - name: git_scm_resource
    type: git
    source:
      uri: https://github.com/andy-john-thompson/concourse-ci-basic.git
      branch: master
jobs:
  - name: job-compile-code
    public: true
    plan:
    - get: git_scm_resource
    - task: task-compile-code
      file: git_scm_resource/examples/pipeline_basic_1/tasks/task_1.yml